export const MAP_PEER_CATALOG = {
  'hanna-b': {
    id: 'hanna-b',
    name: 'Hanna B.',
    initials: 'HB',
    grade: 'Grade 10',
    school: 'Bole Secondary School',
    subjects: ['Mathematics', 'Physics'],
    isMapPeer: true,
  },
  'daniel-m': {
    id: 'daniel-m',
    name: 'Daniel M.',
    initials: 'DM',
    grade: 'Grade 11',
    school: 'St. Joseph School',
    subjects: ['Biology', 'Chemistry'],
    isMapPeer: true,
  },
  'meron-a': {
    id: 'meron-a',
    name: 'Meron A.',
    initials: 'MA',
    grade: 'Grade 12',
    school: 'Addis Ababa Secondary School',
    subjects: ['Mathematics', 'English'],
    isMapPeer: true,
  },
  'yosef-k': {
    id: 'yosef-k',
    name: 'Yosef K.',
    initials: 'YK',
    grade: 'Grade 11',
    school: 'Lideta Secondary School',
    subjects: ['Physics', 'Mathematics'],
    isMapPeer: true,
  },
  'tigist-h': {
    id: 'tigist-h',
    name: 'Tigist H.',
    initials: 'TH',
    grade: 'Grade 9',
    school: 'Kazanchis Academy',
    subjects: ['Mathematics', 'English'],
    isMapPeer: true,
  },
  'abenezer-l': {
    id: 'abenezer-l',
    name: 'Abenezer L.',
    initials: 'AL',
    grade: 'Grade 12',
    school: 'Menelik II School',
    subjects: ['Chemistry', 'Biology'],
    isMapPeer: true,
  },
  'ruth-n': {
    id: 'ruth-n',
    name: 'Ruth N.',
    initials: 'RN',
    grade: 'Grade 10',
    school: 'International Community School',
    subjects: ['English', 'History'],
    isMapPeer: true,
  },
  'yonas-alem': {
    id: 'yonas-alem',
    name: 'Yonas Alem',
    initials: 'YA',
    grade: 'Grade 12',
    school: 'Addis Ababa Secondary School',
    subjects: ['Mathematics', 'Physics'],
    isMapPeer: true,
  },
  'dawit-girma': {
    id: 'dawit-girma',
    name: 'Dawit G.',
    initials: 'DG',
    grade: 'Grade 12',
    school: 'Addis Ababa Secondary School',
    subjects: ['Mathematics', 'Physics'],
    isMapPeer: true,
  },
  'sara-bek': {
    id: 'sara-bek',
    name: 'Sara Bekele',
    initials: 'SB',
    grade: 'Grade 11',
    school: 'Hawassa Secondary School',
    subjects: ['Physics', 'Chemistry'],
    isMapPeer: true,
  },
}

